image: seo.disparate/gcc-runner:latest


stages:
    - build
    - test

buildJob:
    stage: build
    artifacts:
        paths:
            - buildDebug/
    tags:
        - docker
    script:
        - mkdir -p buildDebug
        - cd buildDebug
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=True ../src
        - make

testJob:
    stage: test
    tags:
        - docker
    script:
        - cd buildDebug
        - ./UnitTests

