stages:
    - build
    - test

buildJob:
    stage: build
    script:
        - mkdir buildDebug
        - cd buildDebug
        - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=True ../src
        - make

testJob:
    stage: test
    script:
        - cd buildDebug
        - ./UnitTests

